name: WonCore
version: '1.0'
main: fr.world.nations.Core
api-version: 1.20
author: Holo795
website: https://github.com/Holo795
depend:
  - Factions
  - Vault
commands:
#  warzone:
#    description: warzone